// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbC1pXblhg1NDoS-mRYJtOWQHsBrZiqbc',
    appId: '1:621287431645:web:f5c7eb564612f54ff0ea34',
    messagingSenderId: '621287431645',
    projectId: 'exercise8-dd32f',
    authDomain: 'exercise8-dd32f.firebaseapp.com',
    storageBucket: 'exercise8-dd32f.appspot.com',
    measurementId: 'G-C0LKHVTB1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ43kr42_aeidv82mWS0K2z0S8n9EkgYg',
    appId: '1:621287431645:android:e6a184b817276e9af0ea34',
    messagingSenderId: '621287431645',
    projectId: 'exercise8-dd32f',
    storageBucket: 'exercise8-dd32f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABLwXjUPP4IZYaLadQk_FczH48J2WC9t4',
    appId: '1:621287431645:ios:e5db4cab62f7e2adf0ea34',
    messagingSenderId: '621287431645',
    projectId: 'exercise8-dd32f',
    storageBucket: 'exercise8-dd32f.appspot.com',
    iosClientId: '621287431645-ntipfeqq2m39a2rvqfhec3gtbg2h254u.apps.googleusercontent.com',
    iosBundleId: 'com.ex8.app',
  );
}
