// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgDtji3_68cTYWB5TqtWIxna_82EEQz3A',
    appId: '1:27527123612:web:c13fdbabfd2f9d6df09359',
    messagingSenderId: '27527123612',
    projectId: 'exercise9-e5607',
    authDomain: 'exercise9-e5607.firebaseapp.com',
    storageBucket: 'exercise9-e5607.appspot.com',
    measurementId: 'G-KD32BE1BHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-V1nMNoXjATwLRGM_0Xi6YX-jFEiU6vE',
    appId: '1:27527123612:android:4eb645571b20d79af09359',
    messagingSenderId: '27527123612',
    projectId: 'exercise9-e5607',
    storageBucket: 'exercise9-e5607.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB64aGK29ighnuH_QB1Bk3TbjjMo-wiiKI',
    appId: '1:27527123612:ios:917116ae6e859b98f09359',
    messagingSenderId: '27527123612',
    projectId: 'exercise9-e5607',
    storageBucket: 'exercise9-e5607.appspot.com',
    iosClientId: '27527123612-aj9nrnbqpual0ma3o7odtnit14ib7o20.apps.googleusercontent.com',
    iosBundleId: 'com.ex9.app',
  );
}
